//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf3.ServiceProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/webservicejghz")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf3.ServiceProducto.Cliente))]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/webservicejghz")]
    [System.SerializableAttribute()]
    public partial class Cliente : Wcf3.ServiceProducto.Respuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_Materno {
            get {
                return this.Apellido_MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_MaternoField, value) != true)) {
                    this.Apellido_MaternoField = value;
                    this.RaisePropertyChanged("Apellido_Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_Paterno {
            get {
                return this.Apellido_PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_PaternoField, value) != true)) {
                    this.Apellido_PaternoField = value;
                    this.RaisePropertyChanged("Apellido_Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Res", Namespace="http://schemas.datacontract.org/2004/07/webservicejghz")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf3.ServiceProducto.Alumno))]
    public partial class Res : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/webservicejghz")]
    [System.SerializableAttribute()]
    public partial class Alumno : Wcf3.ServiceProducto.Res {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_ControlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Control {
            get {
                return this.Num_ControlField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_ControlField, value) != true)) {
                    this.Num_ControlField = value;
                    this.RaisePropertyChanged("Num_Control");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REST", Namespace="http://schemas.datacontract.org/2004/07/webservicejghz")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wcf3.ServiceProducto.Producto))]
    public partial class REST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/webservicejghz")]
    [System.SerializableAttribute()]
    public partial class Producto : Wcf3.ServiceProducto.REST {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClasificaciónField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string inventarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clasificación {
            get {
                return this.ClasificaciónField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasificaciónField, value) != true)) {
                    this.ClasificaciónField = value;
                    this.RaisePropertyChanged("Clasificación");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inventario {
            get {
                return this.inventarioField;
            }
            set {
                if ((object.ReferenceEquals(this.inventarioField, value) != true)) {
                    this.inventarioField = value;
                    this.RaisePropertyChanged("inventario");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerCliente", ReplyAction="http://tempuri.org/IService1/ObtenerClienteResponse")]
        Wcf3.ServiceProducto.Cliente ObtenerCliente(string Identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerCliente", ReplyAction="http://tempuri.org/IService1/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<Wcf3.ServiceProducto.Cliente> ObtenerClienteAsync(string Identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAlumno", ReplyAction="http://tempuri.org/IService1/ObtenerAlumnoResponse")]
        Wcf3.ServiceProducto.Alumno ObtenerAlumno(int Semestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAlumno", ReplyAction="http://tempuri.org/IService1/ObtenerAlumnoResponse")]
        System.Threading.Tasks.Task<Wcf3.ServiceProducto.Alumno> ObtenerAlumnoAsync(int Semestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProducto", ReplyAction="http://tempuri.org/IService1/ObtenerProductoResponse")]
        Wcf3.ServiceProducto.Producto ObtenerProducto(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProducto", ReplyAction="http://tempuri.org/IService1/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<Wcf3.ServiceProducto.Producto> ObtenerProductoAsync(int Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Wcf3.ServiceProducto.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Wcf3.ServiceProducto.IService1>, Wcf3.ServiceProducto.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wcf3.ServiceProducto.Cliente ObtenerCliente(string Identificador) {
            return base.Channel.ObtenerCliente(Identificador);
        }
        
        public System.Threading.Tasks.Task<Wcf3.ServiceProducto.Cliente> ObtenerClienteAsync(string Identificador) {
            return base.Channel.ObtenerClienteAsync(Identificador);
        }
        
        public Wcf3.ServiceProducto.Alumno ObtenerAlumno(int Semestre) {
            return base.Channel.ObtenerAlumno(Semestre);
        }
        
        public System.Threading.Tasks.Task<Wcf3.ServiceProducto.Alumno> ObtenerAlumnoAsync(int Semestre) {
            return base.Channel.ObtenerAlumnoAsync(Semestre);
        }
        
        public Wcf3.ServiceProducto.Producto ObtenerProducto(int Codigo) {
            return base.Channel.ObtenerProducto(Codigo);
        }
        
        public System.Threading.Tasks.Task<Wcf3.ServiceProducto.Producto> ObtenerProductoAsync(int Codigo) {
            return base.Channel.ObtenerProductoAsync(Codigo);
        }
    }
}
